# file: roles/common/tasks/main.yml

  - name: dump all vars to /root/ansible.allvars
    action: template src=templates/dumpall.j2 dest=/root/ansible.allvars
    tags: dump-vars

  #  Enable SELinux
  # - selinux:
  #     policy: targeted
  #     state: enforcing
  #   tags: selinux-enforcing

  # Disable SELinux
  - selinux:
      state: disabled
    tags: selinux-disabled
