- hosts: all
  become: true
  strategy: free
  gather_facts: true
  roles:
    - common
    - ntp

- hosts: glusterfs_server_group
  strategy: linear
  roles:
    - glusterfs-server

- hosts: glusterfs_client_group
  strategy: linear
  roles:
    - glusterfs-client

- hosts: glusterserver1
  strategy: linear
  roles:
    - heketi
