# file: roles/tower-server/tasks/main.yml
  - include: install_tower_packages.yml
    tags: install-tower-packages

  - include: ansible_tower_user.yml
    tags: ansible-tower-user

  - include: ansible-configure.yml
    tags: ansible-configure
