# these variables override all others

# ansible tower vars
ans_user: ansuser
ans_pass: anspass

# timezone and ntp servers
# Change to suit you situation/location
timezone: Europe/Amsterdam
ntp_server: [0.nl.pool.ntp.org, 1.nl.pool.ntp.org]

# defaults file for glusterfs-server
gluster_package_version: '38'

# SSH keys
known_hosts_file: "~/.ssh/known_hosts"

# Virtual IP config
glusterserver1_vip: "10.42.0.31"
glusterserver2_vip: "10.42.0.32"
glusterserver3_vip: "10.42.0.33"
ifname_main: "enp0s8"
ifname_vip: "enp0s8:0"

# Ganesha
ha_base_dir: "/var/run/gluster/shared_storage/nfs-ganesha"
# #Creating a high availability cluster and exporting the volume
ha_name: "ganesha-ha-360"
cluster_nodes: [ glusterserver1, glusterserver2, glusterserver3 ]
vip: [ 10.42.0.31, 10.42.0.32, 10.42.0.33 ]
volname: "ganesha"

# defaults file for glusterfs-clients
gluster_server_name: "10.42.0.31"
gluster_share_dir: "/nfs-ganesha/share"
gluster_share_user: "vagrant"
gluster_share_group: "root"
gluster_share_perm: "750"

# [firewalld]
firewall_state: "enabled"
firewall_action: "add"
firewall_ports: [ 111/tcp, 2049/tcp, 54321/tcp, 5900/tcp, 5900-6923/tcp, 5666/tcp, 16514/tcp, 662/tcp, 662/udp ]
firewall_services: [ glusterfs, nfs, rpc-bind, high-availability, mountd ]
firewall_permanent: "true"
firewall_zone: "public"
