# file: roles/common/tasks/main.yml

  - name: dump all vars to /root/ansible.allvars
    action: template src=templates/dumpall.j2 dest=/root/ansible.allvars
    tags: dump-vars

  - name: create ans_user
    command: useradd -m {{ ans_user }} creates=/home/{{ ans_user }}

  - name: set user password
    shell: usermod -p $(echo '{{ ans_pass }}' | openssl passwd -1 -stdin) {{ ans_user }}

  - name: update sudoers file and validate
    lineinfile: "dest=/etc/sudoers
      insertafter=EOF
      line='{{ ans_user }} ALL=(ALL) NOPASSWD: ALL'
      regexp='{{ ans_user }} ALL=(ALL) NOPASSWD: ALL'
      state=present"

  # Example action to restart network service for interface eth0
  - name: restart netowrk
    service:
      name: network
      state: restarted

  #  Enable SELinux
  # - selinux:
  #     policy: targeted
  #     state: enforcing
  #   tags: selinux-enforcing

  # Disable SELinux
  # - selinux:
  #     state: disabled
  #   tags: selinux-disabled
