# these variables override all others

# defaults file for glusterfs-server

gluster_package_version: '37'
gluster_filesystem: "xfs"
gluster_brick_dir: "/glusterfs/brick1"
gluster_volume_name: "tri-repvol01"
gluster_replicas: "3"

# defaults file for glusterfs-clients

gluster_server_name: "glusterserver1"
gluster_share_dir: "/glusterfs/share"
gluster_share_user: "vagrant"
gluster_share_group: "root"
gluster_share_perm: "750"
