---

  - name: make sure everything is mounted
    command: mount -a
    args:
      warn: no

  - name: fixing ganesha configs
    blockinfile:
      dest: "{{ ha_base_dir }}/ganesha.conf"
      backup: yes
      block: |
        NFS_Core_Param {
              #Use supplied name other tha IP In NSM operations
              NSM_Use_Caller_Name = true;
              #Copy lock states into "/var/lib/nfs/ganesha" dir
              Clustered = false;
              #By default port number '2049' is used for NFS service.
              #Configure ports for MNT, NLM, RQuota services.
              #The ports chosen here are from '/etc/sysconfig/nfs'
              MNT_Port = 20048;
              NLM_Port = 32803;
              Rquota_Port = 875;
        }
    run_once: true

  - name: copy ganesha.conf to config directory on shared volume
    copy:
      remote_src: true
      src: "{{ ha_base_dir }}/ganesha.conf"
      dest: /etc/ganesha/
      owner: root
    ignore_errors: yes

  - name: copy ganesha-ha.conf to config directory on shared volume
    copy:
      remote_src: true
      src: "{{ ha_base_dir }}/ganesha-ha.conf"
      dest: /etc/ganesha/
      owner: root
    ignore_errors: yes

  - name: unexport nfs shared
    command: gluster volume set "{{ volname }}" ganesha.enable off --mode=script
    ignore_errors: yes

  - name: Pause for 5 seconds (takes a while to disable NFS)
    pause: seconds=5

  - name: run ganesha-ha.sh
    command: /usr/libexec/ganesha/ganesha-ha.sh --setup /var/run/gluster/shared_storage/nfs-ganesha

  - name: Pause for 15 seconds (takes a while to enable NFS Ganesha)
    pause: seconds=15

  - name: check NFS Ganesha status
    shell: /usr/libexec/ganesha/ganesha-ha.sh --status "{{ ha_base_dir }}" | \
           grep 'Cluster HA Status'
    register: result
    ignore_errors: yes

  - name: report NFS Ganesha status
    debug: msg={{ result.stdout }} verbosity=0
    when: result.stderr == ""

  - name: Rreport NFS Ganesha status (If any errors)
    debug: msg={{ result.stderr }} verbosity=0
    when: result.stderr != ""

  - name: enable ganesha related services
    systemd:
      name: "{{ item }}"
      enabled: yes
    with_items:
      - rpc-statd
      - pacemaker
    register: start
    tags: ganesha-services
