---
# tasks file for glusterfs-server

  - include: install_packages.yml
    tags: install-packages
  # - include: setup_vips.yml
  #   tags: setup-vips
  # - include: setup_firewall.yml
  #   tags: setup-firewall
  - include: disable_firewall.yml
    tags: stop-firewall
  - include: setup_keys.yml
    tags: setup-keys
  - include: setup_keys.yml # Running this twice to besure the keys are there
    tags: setup-keys
  - include: prep_gdeploy.yml
    tags: prep-gdeploy
  - include: setup_ganesha.yml
    run_once: true
    tags: setup-ganesha
  - include: fix_ganesha.yml
    tags: fix-ganesha
