---
# tasks file for glusterfs-server

  - include: install_packages.yml
    tags: install-packages
  - include: setup_vips.yml
    tags: setup-vips
  - include: setup_firewall.yml
    tags: setup-firewall
  - include: setup_keys.yml
    tags: setup-keys
  - include: setup_ganesha.yml
    run_once: true
    tags: setup-ganesha

  # Enable SELinux
  # - selinux:
  #     policy: targeted
  #     state: enforcing
  #   tags: selinux-enforcing

  # Disable SELinux
  - selinux:
      state: disabled
    tags: selinux-disabled
