---

  - name: upload gdeploy config files
    synchronize:
      src: "{{ item }}"
      dest: "/root/"
    with_items:
      - sample.conf
      - setup-ganesha.conf
      - destroy-ganesha.conf
      - remove-volume.conf

  - name: check if setup-ganesha.conf is found
    stat:
      path: /root/setup-ganesha.conf
    register: setup

  - name: running gdeploy setup-ganesha.conf
    command: gdeploy -c /root/setup-ganesha.conf
    register: gedeploy
    when: setup.stat.exists

  - name: check gedploy output
    debug: msg="{{ gdeploy.stdout }}"
