---

  - stat: path=/root/.ssh/id_rsa
    register: root_key

  - name: setting up root key for gdeploy
    command: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
    when: root_key.stat.exists == false

  - name: fetch all public ssh keys
    shell: cat ~/.ssh/id_rsa.pub
    register: ssh_keys
    tags:
      - ssh

  - name: check keys
    debug: msg="{{ ssh_keys.stdout }}"
    tags:
      - ssh

  - name: deploy keys on all servers
    authorized_key: user=root key="{{ item[0] }}"
    delegate_to: "{{ item[1] }}"
    with_nested:
      - "{{ ssh_keys.stdout }}"
      - "{{groups['glusterfs_server_group']}}"
    tags:
      - ssh
